### ISSUE TITLE
What is the history id in the proto

### ISSUE THREAD

**Issue by Jnesselr** [natekspencer/vivintpy#172]
Hello,

I noticed that there was a history_record_id on the GetHistoryClipURLRequest, but I can't figure out how to essentially get a list of these object id's. I'm not sure if that's just not a listed method or what.

**Comment by natekspencer** [comment]
I haven't tried to dive in to most of the gRPC code, so I honestly don't know.

**Comment by Jnesselr** [comment]
May I ask where you got the gRPC code? Yours was the only instance of it that I found. I'm mostly trying to get like 8 hours worth of footage from my cameras and can't figure out how to do that easily.

**Comment by natekspencer** [comment]
It was from the Android APK
